namespace Toub.Sound.Midi
{
    using System;

    [Serializable]
    public enum Controllers : byte
    {
        AllControllersOff = 0x79,
        AllNotesOff = 0x7b,
        AllSoundOff = 120,
        BalanceCourse = 8,
        BalanceFine = 40,
        BankSelectCourse = 0,
        BankSelectFine = 0x20,
        BreathControllerCourse = 2,
        BreathControllerFine = 0x22,
        CelesteLevel = 0x5e,
        ChorusLevel = 0x5d,
        DataButtonDecrement = 0x61,
        DataButtonIncrement = 0x60,
        DataEntryCourse = 6,
        DataEntryFine = 0x26,
        EffectControl1Course = 12,
        EffectControl1Fine = 0x2c,
        EffectControl2Course = 13,
        EffectControl2Fine = 0x2d,
        EffectsLevel = 0x5b,
        ExpressionCourse = 11,
        ExpressionFine = 0x2b,
        FootPedalCourse = 4,
        FootPedalFine = 0x24,
        GeneralPurposeButton1OnOff = 80,
        GeneralPurposeButton2OnOff = 0x51,
        GeneralPurposeButton3OnOff = 0x52,
        GeneralPurposeButton4OnOff = 0x53,
        GeneralPurposeSlider1 = 0x10,
        GeneralPurposeSlider2 = 0x11,
        GeneralPurposeSlider3 = 0x12,
        GeneralPurposeSlider4 = 0x13,
        Hold2PedalOnOff = 0x45,
        HoldPedalOnOff = 0x40,
        LegatoPedalOnOff = 0x44,
        LocalKeyboardOnOff = 0x7a,
        ModulationWheelCourse = 1,
        ModulationWheelFine = 0x21,
        MonoOperation = 0x7e,
        NonRegisteredParameterCourse = 0x63,
        NonRegisteredParameterFine = 0x62,
        OmniModeOff = 0x7c,
        OmniModeOn = 0x7d,
        PanPositionCourse = 10,
        PanPositionFine = 0x2a,
        PhaserLevel = 0x5f,
        PolyOperation = 0x7f,
        PortamentoOnOff = 0x41,
        PortamentoTimeCourse = 5,
        PortamentoTimeFine = 0x25,
        RegisteredParameterCourse = 0x65,
        RegisteredParameterFine = 100,
        SoftPedalOnOff = 0x43,
        SoundAttackTime = 0x49,
        SoundBrightness = 0x4a,
        SoundControl10 = 0x4f,
        SoundControl6 = 0x4b,
        SoundControl7 = 0x4c,
        SoundControl8 = 0x4d,
        SoundControl9 = 0x4e,
        SoundReleaseTime = 0x48,
        SoundTimbre = 0x47,
        SoundVariation = 70,
        SustenutoPedalOnOff = 0x42,
        TremuloLevel = 0x5c,
        VolumeCourse = 7,
        VolumeFine = 0x27
    }
}

